### ISSUE TITLE
App Crashes When Download Button is Clicked Without a Download Link

### ISSUE THREAD

**Issue by onlyheram42** [MeetRajput00/DownloadManager#18]
Summary: The app crashes when the download button is clicked if there is no download link provided.

Steps to Reproduce:

Open the app.
Ensure there is no download link available.
Click the download button.
Expected Behavior: The app should handle the absence of a download link gracefully and show an appropriate message or handle the situation without crashing.

Actual Behavior: The app crashes when the download button is clicked without a valid download link.

Labels: bug, crash

**Comment by MeetRajput00** [comment]
#19 fixes this. @onlyheram42
